#ifndef CONSTANTS_PRIMARY_H
#define CONSTANTS_PRIMARY_H

#define INITIAL_INFECTION_RATE 0.01f
#define INITIAL_HEALTHY_RATE 0.2f
#define NATURAL_DEATH_CHANCE 0.001f
#define DEAD_REVIVAL_RATE 0.001f

#define DEFAULT_INFECTIVITY 0.3f
#define DEFAULT_SEVERITY 0.5f
#define DEFAULT_MUTATION_RATE 0.005f

#endif