#ifndef CONSTANTS_VACCINATION_H
#define CONSTANTS_VACCINATION_H

#define DEFAULT_VACCINATION_RATE 0.0f
#define VACCINATION_EFFECTIVENESS 0.9f
#define VACCINATION_SPONTANEOUS_RATE 0.001f
#define VACCINATION_LOSS_RATE 0.0005f

#define MASS_VACCINATION_INTERVAL 75
#define MASS_VACCINATION_COVERAGE 0.7f
#define MASS_VACCINATION_MIN_INTERVAL 25
#define VACCINE_DURATION_MIN 50
#define VACCINE_DURATION_MAX 100

#endif