#ifndef CONSTANTS_EVOLUTION_H
#define CONSTANTS_EVOLUTION_H

#define SEVERE_INFECTION_MORTALITY_BOOST 0.4f
#define SEVERE_INFECTION_SPREAD_BOOST 0.3f
#define IMMUNITY_INHERITANCE_CHANCE 0.7f
#define IMMUNITY_BOOST_PER_GENERATION 0.1f
#define MAX_IMMUNITY_BOOST 0.5f
#define REPRODUCTION_CHANCE 0.005f
#define REPRODUCTION_IMMUNITY_BONUS 0.3f

#endif