#ifndef CONSTANTS_INFECTION_H
#define CONSTANTS_INFECTION_H

#define IMMUNITY_STAGE_COUNT 4
#define INFECTION_STAGE_COUNT 4

#define NEIGHBORHOOD_RADIUS 1
#define MAX_RESISTANCE 7
#define MIN_SURVIVAL_CHANCE 0.1f
#define RESISTANCE_PROTECTION_FACTOR 0.7f
#define DISTANCE_ATTENUATION 1.5f

#endif